### ISSUE TITLE
maka g:scaffold command doesn't work at all

### ISSUE THREAD

**Issue by kunwarVivek** [maka-io/maka-cli#1]
Hi,

I created a blaze application using maka. 
"maka g:scaffold todos: command does not generate any output.

The node version is 14.x and maka-cli is the latest version 3.2.67

I wanted to experiment with maka before starting the manual creation

**Comment by maka-io** [comment]
Hi @kunwarVivek ,

Sorry about that! There has been some transition and the scaffold command was missed :(

I just pushed an update, please update to 3.2.68 and try your command again.

Thanks!

**Comment by kunwarVivek** [comment]
Thanks. It is working well now.
