### ISSUE TITLE
--client=react missing test-helpers.js.jsx file

### ISSUE THREAD

**Issue by kraegpoeth** [maka-io/maka-cli#16]
So im giving you cli tool a try and wanted to try it out with react. The maka create --client=react command complained that there was no test-helpers.js.jsx file when scafolding out the project folder. Specifically: 
`Error: Couldn't find a source template in "/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/templates/app/imports/ui/test-helpers.js.jsx"
`
Fixed the issue but just dublicating the test-helpers.js file and appended .jsx to it. 
Small bug thats easy to fix.. Maybe because i am running node through nvm?
maka-cli@2.5.27

Now the server is running - great tool so far!

Thanks
-Kasper

**Comment by maka-io** [comment]
hey @kraegpoeth Sorry this took sooooo long for me to get back to you.  Just had  new baby and my attention was slightly elsewhere!

I did see that issue, and I hope I got it pretty much squashed in a previous release.  Please let me know if this is still a problem.

Thanks!

**Comment by kraegpoeth** [comment]
Hey @maka-io 
No worries and big congrats on the new one. I will try your tool again in the next project then. Any chance of you extending to React Native as well?

Thanks,
Kasper

**Comment by maka-io** [comment]
@kraegpoeth I'll put that on the list!  I was looking at it while I was finishing up with React, but got distracted by the shiny Apollo GraphQL stuff.  So to answer your question, there's a pretty good chance!

**Comment by ajaybhatia** [comment]
> hey @kraegpoeth Sorry this took sooooo long for me to get back to you. Just had new baby and my attention was slightly elsewhere!
> 
> I did see that issue, and I hope I got it pretty much squashed in a previous release. Please let me know if this is still a problem.
> 
> Thanks!

A big congratulations to whole family! Love to cutie!!

**Comment by kraegpoeth** [comment]
hey @maka-io 
So ive been around to different stuff and wanted to test out the updated maka-cli and the test-helpers file is still named incorrectly. Got the following error:

/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Couldn't find a source template in "/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/templates/app/imports/ui/test-helpers.js.jsx"
    at Command.templateContent (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:374:15)
    at Command.template (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:388:33)
    at /Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:456:18
    at Function._.each._.forEach (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/node_modules/underscore/underscore.js:153:9)
    at Command.copyTemplateDirectory (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:445:7)
    at /Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:453:18
    at Function._.each._.forEach (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/node_modules/underscore/underscore.js:153:9)
    at Command.copyTemplateDirectory (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:445:7)
    at /Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/lib/tools/file_system.js:453:18
    at Function._.each._.forEach (/Users/krgpth/.nvm/versions/node/v7.5.0/lib/node_modules/maka-cli/node_modules/underscore/underscore.js:153:9)

Renamed the file to test-helpers.js.jsx and the maka-create ReactApp --client=react worked like a charm. Thanks again for a really nice tool!

**Comment by maka-io** [comment]
@kraegpoeth Ok, let me get my windows machine up and running and get that fixed!

**Comment by maka-io** [comment]
Fixed in 2.6.9!
