### ISSUE TITLE
maka create --client=blaze error

### ISSUE THREAD

**Issue by VivekMgw** [maka-io/maka-cli#2]
The default blaze app generated with the command "maka create <test-app> --client=blaze " fails to generate a working app. 

The generated code compiles and generates console error on the run.

meteor - 2.1.1
npm - 7.9.0
node - 14.16.1

Let me know if you need additional information.

**Comment by maka-io** [comment]
Hey @VivekMgw ,

I just pushed up a patch to address that issue (v.3.2.69), please let me know if the new version works out!
