### ISSUE TITLE
more info on generators in readme

### ISSUE THREAD

**Issue by honkskillet** [maka-io/maka-cli#41]
It would be good if the readme gave more info on the generators.  Ie, what files will be made (or altered?) when a specific generator is run and (in one sentence) what the purpose of a given generator is.

**Comment by maka-io** [comment]
@honkskillet Great suggestion.  I know my documentation is not great -- I'll update the documentation on the generator section asap.

Thanks for your feedback!

**Comment by maka-io** [comment]
@honkskillet I've been trying to get these generators defined.  Here is a write up of the API generator, and my up and coming website:
[Organize your Meteor Application with Maka-CLI Generators, Part 1: API](https://medium.com/@matthewjmcampbell/organize-your-meteor-application-with-maka-cli-generators-part-1-api-c4046ea1bde3)
[maka-cli.org](https://maka-cli.org) .. give it a minute to start up... I still have it on the free "Heroku" plan.

I'm going to close this, maybe follow me on medium.com and you can stay up to date on more generator stuff.
