### ISSUE TITLE
Navbar with react-router in maka?

### ISSUE THREAD

**Issue by myrtleTree33** [maka-io/maka-cli#44]
Hi!

I'm just wondering if someone would be able to provide a code snippet of using Links with react-router in maka.  Been trying to get Links to work, but somehow the links disappear upon render.

**Comment by maka-io** [comment]
Hey @myrtleTree33 ,  check out an article I published on (medium)[https://medium.com/@matthewjmcampbell/scaffold-material-ui-themed-react-web-applications-with-maka-cli-ddef6864c7c0].  It used Material-UI to render an AppBar component, but you can easily replace the AppBar with any ol' <div> or <ul> and setup your navbar.  If you give me a minute, I can wrangle up an example I have laying around.

**Comment by maka-io** [comment]
Ok, Step 1:
(With whatever options you need).
```sh
maka create app-with-nav
```

Step 2:
Change into app and then create the navbar component:
```sh
maka g:t navbar --component
```

Step 3:
Make an additional route to nav to:
```sh
maka g:route contact
```

Step 4:
Open up the master-layout.jsx file and include your navbar:
(/imports/ui/layouts/master-layout/master-layout.jsx)
```js
import './master-layout.css';
import React, { Component } from 'react';

import { Navbar } from '/imports/ui/components/navbar/navbar';

class MasterLayoutComponent extends Component {
  static propTypes = {}

  static defaultProps = {}

  constructor(props) {
    super(props);
    this.state = {};
  }

  componentWillMount() {
  }

  componentDidMount() { }

  componentWillUnmount() {
  }

  render() { 
    return (
      <div>
        <Navbar/>
        { this.props.children }
      </div>
    );
  }
}

const MasterLayout = MasterLayoutComponent;
export { MasterLayout };
```

Step 5:
Update your navbar:
(/app/imports/ui/components/navbar/navbar.jsx)

Note:
* Import browserHistory
* Add new method to handle the onMouseUp event (route())
* I left out withTracker in this example

```js
import './navbar.css';
import React, { Component } from 'react';

import { browserHistory } from 'react-router';

class NavbarComponent extends Component {
  static propTypes = {}

  static defaultProps = {}

  constructor(props) {
    super(props);
    this.state = {};

    this.style = {
      container: {
        display: 'flex'
      },
      items: {
        padding: 10,
        cursor: 'pointer'
      }
    }
  }

  componentWillMount() { }

  componentDidMount() { }

  componentWillUnmount() { }

  route = (url) => {
    browserHistory.push(url);
  }

  render() {
    const style = this.style;

    return (
      <div style={style.container}>
        <div style={style.items} onMouseUp={() => {this.route('/')}}>Home</div>
        <div style={style.items} onMouseUp={() => {this.route('/contact')}}>Contact</div>
      </div>
    );
  }
}
const Navbar = NavbarComponent;

export { Navbar };
```

**Comment by maka-io** [comment]
@myrtleTree33 Let me know if you need any more help!
