### ISSUE TITLE
'maka' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by webmagnets** [maka-io/maka-cli#5]
I'm on Windows 11. I ran `npm i -g @maka/maka-cli@latest` in the command line. Then when I ran `maka create my-app --theme=material` I got an error that said `'maka' is not recognized as an internal or external command, operable program or batch file.`

Any ideas?

**Comment by maka-io** [comment]
It could be how NPM is setup, do you have the NPM execution directory in your PATH?

**Comment by maka-io** [comment]
@webmagnets did that help?

**Comment by webmagnets** [comment]
I haven't had time to try. You can close this ticket if you want. I will try later. Thank you very much for your help.

--
Nathan Cain
501-463-6336
jw.org

On September 28, 2022 at 15:09 GMT, Matt Campbell ***@***.***> wrote:

***@***.***(https://github.com/webmagnets) did that help?
