### ISSUE TITLE
Quickstart Example

### ISSUE THREAD

**Issue by kingzuru** [maka-io/maka-cli#56]
Is there anywhere where I can find working examples of maka, something like a Todo App will be great so that new users like me can easily follow and understand through practical examples.

**Comment by maka-io** [comment]
You could head over to my Medium posts:
https://medium.com/@matthewjmcampbell/build-your-webapp-with-meteor-maka-cli-629b7b16831d

**Comment by maka-io** [comment]
https://medium.com/@matthewjmcampbell/organize-your-meteor-application-with-maka-cli-generators-part-1-api-c4046ea1bde3

**Comment by maka-io** [comment]
I haven't been able to write as many as I'd like, mainly because of other work stuff... plan to get started again though!

**Comment by kingzuru** [comment]
> I haven't been able to write as many as I'd like, mainly because of other work stuff... plan to get started again though!

Maybe my question wasn't clear. What I am looking for is how to display data on the frontend. I would appreciate it if you could atleast show an example or a code snippet for doing that. Thanks in advance.

**Comment by maka-io** [comment]
Ah, yeah not clear.  Here is a code snippet:

```
    $ maka create NewApp
```

wait for it to finish

```
   $ cd NewApp
   $ maka
````

You'll then see that your meteor site is running on localhost:3000 (open that page).

On that page you'll find the location (relative to the app directory) of the file that is displaying that text (/imports/ui/pages/home/home.jsx)

Open that file.

In there, head over to the "render()" method and you'll find the text that generates what you see in your web browser.

That is (a snippet) of how data is displayed.  Now, by default Maka-CLI sets up your app to use React.  So all normal React stuff applies (head over to the React website / training google results for more info).  If you want to use Blaze (Meteor's UI) then you'll need to create your app with the --client=blaze modifier.

```
    $ maka create BlazeApp --client=blaze
```

**Comment by kingzuru** [comment]
> Ah, yeah not clear. Here is a code snippet:
> 
> ```
>     $ maka create NewApp
> ```
> wait for it to finish
> 
> ```
>    $ cd NewApp
>    $ maka
> ```
> You'll then see that your meteor site is running on localhost:3000 (open that page).
> 
> On that page you'll find the location (relative to the app directory) of the file that is displaying that text (/imports/ui/pages/home/home.jsx)
> 
> Open that file.
> 
> In there, head over to the "render()" method and you'll find the text that generates what you see in your web browser.
> 
> That is (a snippet) of how data is displayed. Now, by default Maka-CLI sets up your app to use React. So all normal React stuff applies (head over to the React website / training google results for more info). If you want to use Blaze (Meteor's UI) then you'll need to create your app with the --client=blaze modifier.
> 
> ```
>     $ maka create BlazeApp --client=blaze
> ```

Thanks `$ maka create BlazeApp --client=blaze` that's what I was looking for as I am familiar with Blaze.

**Comment by maka-io** [comment]
@kingzuru Great! Let me know if you need any more help.

**Comment by maka-io** [comment]
@kingzuru I'm working on a document page as well, it's nowhere near finished...but may have some bits you can use:
http://www.maka-cli.org/

**Comment by kingzuru** [comment]
Thanks @maka-io you have been really helpful. Cheers!
