### ISSUE TITLE
cultofcoders apollo fails when working with remote GraphQL servers

### ISSUE THREAD

**Issue by maka-io** [maka-io/maka-cli#61]
@ajaybhatia are you seeing problems when working with remote graphql servers?  I made a fork of cultofcoders:apollo and patched it to allow changing the server address, which works.  However, there is still some strangeness that I haven't worked out yet.

**Comment by maka-io** [comment]
Fixed with https://github.com/maka-io/maka-cli/commit/13ddd3e94d5d0d269e6513262cbbe60477f01361

Cult of coders abstracts too much away from the base Appollo implementation, sorry!

**Comment by ajaybhatia** [comment]
@maka-io Sorry I was busy and unable respond early. I've seen your fix. Is it really fixed for you? I am not facing any issue while using remote graphql server.
