### ISSUE TITLE
Feature Request - Functional Components with Hooks (React)

### ISSUE THREAD

**Issue by ajaybhatia** [maka-io/maka-cli#66]
Hi Matt,

What is your opinion about using Functional components with hooks rather than class components for react client? If you agree on this then we can convert the whole thing to functional components with hooks and also use useTracker rather than withTracker.

Share your thoughts.

**Comment by maka-io** [comment]
Hey Ajay, great to hear form you! Thanks for the suggestion.  I've been trying to figure our how to go about implementing hooks.  I was initially reluctant to whole sale replace Class because of the lack of state management, but seems like that may be solved now in hooks.  Perhaps a flag "--prefer-hooks" on creation of a react app.  Could also be configured in the maka config file for existing apps.  What do you think?

**Comment by ajaybhatia** [comment]
> Hey Ajay, great to hear form you! Thanks for the suggestion. I've been trying to figure our how to go about implementing hooks. I was initially reluctant to whole sale replace Class because of the lack of state management, but seems like that may be solved now in hooks. Perhaps a flag "--prefer-hooks" on creation of a react app. Could also be configured in the maka config file for existing apps. What do you think?

Hey Matt! You're really fast in replying!! Yes flag seems nice option to create FC with hooks. You just start with the code I will follow you and will contribute in implementing it.

**Comment by maka-io** [comment]
Cool! Yeah I'll get on it today and tomorrow.  It's cold and windy out, good days to code 🤓

**Comment by maka-io** [comment]
@ajaybhatia haven't forgotten about this, but just started a new job... I've been swamped! I started making the new template, but had to hit the pause button.  I'm super into hooks now, so it's not far off that I'll have this implemented!

Sorry for the delay!

**Comment by ajaybhatia** [comment]
> @ajaybhatia haven't forgotten about this, but just started a new job... I've been swamped! I started making the new template, but had to hit the pause button. I'm super into hooks now, so it's not far off that I'll have this implemented!
> 
> Sorry for the delay!

Hi Matt! First of congratulations for the new role. I can understand of swamped one be after switching to new job and responsibilty. No issues at all. You take your time. Moreover the whole planet is scared from n-Covid right now and things are as well as it were.

Stay safe, stay healthy!

**Comment by maka-io** [comment]
Hey @ajaybhatia , please hit my up on my email, mjmcee@gmail.com.  A lot of changes for Maka-CLI, and I'd like to offer the contributors of this repo a gift. :D

**Comment by maka-io** [comment]
@ajaybhatia I've finally finished this in version 3.1.8, you can now create hooks with:
```
maka g:hook cool-hook
```

Enjoy!

**Comment by ajaybhatia** [comment]
Great 👌
